### ISSUE TITLE
Tracker for cross-platform

### ISSUE THREAD

**Issue by vbatts** [kubernetes-sigs/cri-o#1588]
This is adding a currently failing target, which once succeeding ought
to be added to some travis check.

Currently blocked by:
- [x] https://github.com/kubernetes-incubator/cri-o/pull/1435
- [x] https://github.com/kubernetes-incubator/cri-o/pull/1421
- [x] https://github.com/kubernetes-incubator/cri-o/pull/1411
- [x] https://github.com/kubernetes-incubator/cri-o/pull/1407
- [x] https://github.com/kubernetes-incubator/cri-o/pull/1505
- [ ] https://github.com/kubernetes-incubator/cri-o/pull/1506
- [ ] https://github.com/kubernetes-incubator/cri-o/pull/1439
- [x] https://github.com/kubernetes-incubator/cri-o/pull/1407
- [x] https://github.com/kubernetes-incubator/cri-o/pull/1504
- [x] https://github.com/kubernetes-incubator/cri-o/pull/1567
- [ ] https://github.com/cri-o/ocicni/pull/19
- [ ] https://github.com/cri-o/ocicni/pull/20
- [x] https://github.com/kubernetes-incubator/cri-o/pull/1596
- [ ] https://github.com/kubernetes-incubator/cri-o/pull/1574

**Comment by rhatdan** [comment]
@vbatts is this still something you are working on, or should I close it?

**Comment by vbatts** [comment]
The cross platform effort for crio got shelved for now
